name: Generate Changelog

on:
  workflow_dispatch:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  GIT_SSH_COMMAND: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
      - run: flutter pub get
      - name: Build identifier
        id: build-identifier
        run: echo "::set-output name=build-identifier::$(echo $(flutter pub run izakaya pub version)_${GITHUB_RUN_NUMBER})"
      - run: echo ${{steps.build-identifier.outputs.build-identifier}}
      - run: mkdir -p docs/changelogs
      - run: flutter pub run izakaya pub changelog "f00" HEAD HEAD~3 > docs/changelogs/build_${{steps.build-identifier.outputs.build-identifier}}.md
