name: Generate Changelog

on:
  push:

defaults:
  run:
    shell: bash

jobs:
  changelog:
    runs-on: ubuntu-latest
    env:
      GIT_SSH_COMMAND: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
    steps:
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: "stable"
      - run: flutter pub run izakaya pub changelog ${GITHUB_RUN_NUMBER} HEAD HEAD~10 > docs/changelog/${GITHUB_RUN_NUMBER}.md
