name: Generate Changelog

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  GIT_SSH_COMMAND: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
      - run: flutter pub get
      - name: Build identifier
        id: build-identifier
        run: echo "::set-output name=build-identifier::$(echo $(flutter pub run izakaya pub version)_${GITHUB_RUN_NUMBER})"
      - run: echo ${{steps.build-identifier.outputs.build-identifier}}
      - name: Create tag
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{ github.token }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{steps.build-identifier.outputs.build-identifier}}",
              sha: context.sha
            })
      # - run: mkdir -p docs/changelogs
      # - run: flutter pub run izakaya pub changelog ${{steps.build-identifier.outputs.build-identifier}} HEAD HEAD~3 > docs/changelogs/build_${{steps.build-identifier.outputs.build-identifier}}.md
