name: Generate Changelog

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  GIT_SSH_COMMAND: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

jobs:
  finalize:
    runs-on: ubuntu-latest
    outputs:
      previous_version: ${{steps.sem-ver.outputs.current}}
      current_version: ${{steps.sem-ver.outputs.previous}}
      changelog: ${{steps.changelog.outputs.changelog}}
    steps:
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
      - run: flutter pub get
      - name: Generate Semantic Versions
        id: sem-ver
        run: |
          echo "::set-output name=current::$(echo $(flutter pub run izakaya pub version -b ${GITHUB_RUN_NUMBER}))"
          echo "::set-output name=previous::$(echo $(flutter pub run izakaya pub version -b $((${GITHUB_RUN_NUMBER}-1))))"
      # Debating on writing this to a temp file or to the repo
      # Gotta do funky stuff because of the multi-line output
      # https://github.community/t/set-output-truncates-multiline-strings/16852/2
      - name: Generate Changelog
        id: changelog
        run: |
          CHANGELOG="$(flutter pub run izakaya pub changelog ${{ steps.sem-ver.outputs.current }} HEAD ${{ steps.sem-ver.outputs.previous }})"
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo "::set-output name=changelog::$(echo $CHANGELOG)"
      # - run: mkdir -p docs/changelogs
      # - run: flutter pub run izakaya pub changelog ${{steps.build-identifier.outputs.build-identifier}} HEAD HEAD~3 > docs/changelogs/build_${{steps.build-identifier.outputs.build-identifier}}.md
      - run: echo "${{ steps.changelog.outputs.changelog }}"
      - name: Create Release
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{ github.token }}
          script: |
            await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{steps.sem-ver.outputs.current}}",
              target_commitish: context.sha,
              body: "${{steps.changelog.outputs.changelog}}",
            })
